<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Submission extends Model
{
	protected $table = 'submissions';
	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	protected $fillable = [
		'uploaded_at',
		'user_id',
		'ip_address',
		'battery_voltage',
		'battery_current',
		'battery_temperature',
		'charge_current',
		'mppt_voltage',
		'solar_n1_current',
		'solar_n2_current',
		'solar_e1_current',
		'solar_e2_current',
		'solar_s1_current',
		'solar_s2_current',
		'solar_w1_current',
		'solar_w2_current',
		'solar_t1_current',
		'solar_t2_current',
		'rails_switch_status',
		'rails_overcurrent_status',
		'rail_1_boot_count',
		'rail_1_overcurrent_count',
		'rail_1_voltage',
		'rail_1_current',
		'rail_2_boot_count',
		'rail_2_overcurrent_count',
		'rail_2_voltage',
		'rail_2_current',
		'rail_3_boot_count',
		'rail_3_overcurrent_count',
		'rail_3_voltage',
		'rail_3_current',
		'rail_4_boot_count',
		'rail_4_overcurrent_count',
		'rail_4_voltage',
		'rail_4_current',
		'rail_5_boot_count',
		'rail_5_overcurrent_count',
		'rail_5_voltage',
		'rail_5_current',
		'rail_6_boot_count',
		'rail_6_overcurrent_count',
		'rail_6_voltage',
		'rail_6_current',
		'3v3_voltage',
		'3v3_current',
		'5v_voltage',
		'5v_current',
	];
	
	public $timestamps = false; //needed because I'm not using the default timestamp columns (updated_at, created_at), and otherwise php artisan tinker craps itself.
	
	public static $validation_rules = [
		'uploaded_at' => 'required|date_format:Y-m-d H:i:s',
		'user_id' => 'integer|exists:users,id',
		'battery_voltage'=>'numeric',
		'battery_current'=>'numeric',
		'battery_temperature'=>'numeric',
		'charge_current'=>'numeric',
		'mppt_voltage'=>'numeric',
		'solar_n1_current'=>'numeric',
		'solar_n2_current'=>'numeric',
		'solar_e1_current'=>'numeric',
		'solar_e2_current'=>'numeric',
		'solar_s1_current'=>'numeric',
		'solar_s2_current'=>'numeric',
		'solar_w1_current'=>'numeric',
		'solar_w2_current'=>'numeric',
		'solar_t1_current'=>'numeric',
		'solar_t2_current'=>'numeric',
		'rails_switch_status'=>'numeric',
		'rails_overcurrent_status'=>'numeric',
		'rail_1_boot_count'=>'numeric',
		'rail_1_overcurrent_count'=>'numeric',
		'rail_1_voltage'=>'numeric',
		'rail_1_current'=>'numeric',
		'rail_2_boot_count'=>'numeric',
		'rail_2_overcurrent_count'=>'numeric',
		'rail_2_voltage'=>'numeric',
		'rail_2_current'=>'numeric',
		'rail_3_boot_count'=>'numeric',
		'rail_3_overcurrent_count'=>'numeric',
		'rail_3_voltage'=>'numeric',
		'rail_3_current'=>'numeric',
		'rail_4_boot_count'=>'numeric',
		'rail_4_overcurrent_count'=>'numeric',
		'rail_4_voltage'=>'numeric',
		'rail_4_current'=>'numeric',
		'rail_5_boot_count'=>'numeric',
		'rail_5_overcurrent_count'=>'numeric',
		'rail_5_voltage'=>'numeric',
		'rail_5_current'=>'numeric',
		'rail_6_boot_count'=>'numeric',
		'rail_6_overcurrent_count'=>'numeric',
		'rail_6_voltage'=>'numeric',
		'rail_6_current'=>'numeric',
		'3v3_voltage'=>'numeric',
		'3v3_current'=>'numeric',
		'5v_voltage'=>'numeric',
		'5v_current'=>'numeric',
	];
}
